
package com.example.demo.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebServiceTest", targetNamespace = "http://service.demo.example.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebServiceTest {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showTwo", targetNamespace = "http://service.demo.example.com", className = "com.example.demo.client.ShowTwo")
    @ResponseWrapper(localName = "showTwoResponse", targetNamespace = "http://service.demo.example.com", className = "com.example.demo.client.ShowTwoResponse")
    public String showTwo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "show", targetNamespace = "http://service.demo.example.com", className = "com.example.demo.client.Show")
    @ResponseWrapper(localName = "showResponse", targetNamespace = "http://service.demo.example.com", className = "com.example.demo.client.ShowResponse")
    public String show(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
