spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
      web-stat-filter:
        enabled: true
  # ShardingJDBC数据分片配置
  shardingsphere:
    datasource:
      names: ds0                                        #数据源名称，多数据源以逗号分隔
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource        #数据库连接池类名称
        driver-class-name: com.mysql.jdbc.Driver            #数据库驱动类名
        url: jdbc:mysql://127.0.0.1:3306/spring-all         #数据库url连接
        username: root                                      #数据库用户名
        password: root                                      #数据库密码
    sharding:
      tables:
        student:
          actual-data-nodes: ds0.student_$->{2022..2023}$->{(1..12).collect{t ->t.toString().padLeft(2,'0')}}    #由数据源名 + 表名组成，以小数点分隔。多个表以逗号分隔，
          table-strategy:
            standard:
              sharding-column: create_time                  #分片列名称
              precise-algorithm-class-name: com.example.shardingjdbc.config.DatePreciseShardingAlgorithm
    props:
      sql:
        show: true                                        #是否开启SQL显示，默认值: false